//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLINFO
    {
        public int IdBillInfo { get; set; }
        public int IdBill { get; set; }
        public string Service { get; set; }
        public int Amount { get; set; }
        public int Price { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
