//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int IdBill { get; set; }
        public int IdBillInfo { get; set; }
        public Nullable<int> Total { get; set; }
        public string Name { get; set; }
        public int IdRental { get; set; }
    
        public virtual BILLINFO BILLINFO { get; set; }
        public virtual RENTAL RENTAL { get; set; }
    }
}
