//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_CONVINIENT
    {
        public int IdConvinientDetail { get; set; }
        public int IdRoom { get; set; }
        public int IdConvinient { get; set; }
        public int Amount { get; set; }
    
        public virtual CONVINIENT CONVINIENT { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
