//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKSEntities : DbContext
    {
        public QLKSEntities()
            : base("name=QLKSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BILLINFO> BILLINFOes { get; set; }
        public virtual DbSet<CATEGORY_ROOM> CATEGORY_ROOM { get; set; }
        public virtual DbSet<CATEGORY_SERVICE> CATEGORY_SERVICE { get; set; }
        public virtual DbSet<CATEGORY_USER> CATEGORY_USER { get; set; }
        public virtual DbSet<CONVINIENT> CONVINIENTs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<DETAIL_CONVINIENT> DETAIL_CONVINIENT { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<RENTAL> RENTALs { get; set; }
        public virtual DbSet<RENTALDETAIL> RENTALDETAILs { get; set; }
        public virtual DbSet<RESERVATION> RESERVATIONs { get; set; }
        public virtual DbSet<RESERVATION_DETAIL> RESERVATION_DETAIL { get; set; }
        public virtual DbSet<ROOM> ROOMs { get; set; }
        public virtual DbSet<SALES_REPORT> SALES_REPORT { get; set; }
        public virtual DbSet<SALES_REPORT_DETAIL> SALES_REPORT_DETAIL { get; set; }
        public virtual DbSet<SERVICE> SERVICEs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
