//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION_DETAIL
    {
        public int IdReservationDetail { get; set; }
        public int IdRoom { get; set; }
        public int IdReservation { get; set; }
        public string Status { get; set; }
    
        public virtual RESERVATION RESERVATION { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
